### ISSUE TITLE
Otter fails to compile with QT 5.5

### ISSUE THREAD

**Issue by n3rdopolis** [OtterBrowser/otter-browser#706]
It seems that I get this error

[ 35%] Building CXX object CMakeFiles/otter-browser.dir/src/core/FileSystemCompleterModel.cpp.o
[ 36%] Building CXX object CMakeFiles/otter-browser.dir/src/core/GesturesManager.cpp.o
[ 37%] Building CXX object CMakeFiles/otter-browser.dir/src/core/HistoryManager.cpp.o
/srcbuild/otter/src/core/CookieJar.cpp: In constructor ‘Otter::CookieJar::CookieJar(bool, QObject*)’:
/srcbuild/otter/src/core/CookieJar.cpp:51:20: error: variable ‘QDataStream stream’ has initializer but incomplete type
  QDataStream stream(&file);
                    ^
/srcbuild/otter/src/core/CookieJar.cpp: In member function ‘virtual void Otter::CookieJar::timerEvent(QTimerEvent*)’:
/srcbuild/otter/src/core/CookieJar.cpp:100:20: error: variable ‘QDataStream stream’ has initializer but incomplete type
  QDataStream stream(&file);
                    ^
CMakeFiles/otter-browser.dir/build.make:709: recipe for target 'CMakeFiles/otter-browser.dir/src/core/CookieJar.cpp.o' failed
make[2]: *** [CMakeFiles/otter-browser.dir/src/core/CookieJar.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/otter-browser.dir/all' failed
make[1]: *** [CMakeFiles/otter-browser.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 44 seconds

**Comment by Emdek** [comment]
I've added extra includes, let me know if something else will show up.
I'll start testing with Qt 5.5 after first beta, now it's too early for that.

**Comment by n3rdopolis** [comment]
That appears to have fixed the compilation. Thanks!
