### ISSUE TITLE
Can't build with Qt5.5.1

### ISSUE THREAD

**Issue by TCH68k** [OtterBrowser/otter-browser#1532]
I've just updated my local repo of Otter and tried to build it. The result is:`CMake Error at CMakeLists.txt:81 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.6.0".

  The following configuration files were considered but not accepted:

    /opt/Qt/5.5/gcc_64/lib/cmake/Qt5/Qt5Config.cmake, version: 5.5.1`

If i edit the CMakeLists.txt and change 5.6.0 to 5.5.1 at line 81, then it results in:`opt/otter/src/core/NetworkManagerFactory.cpp: In static member function ‘static QNetworkReply* Otter::NetworkManagerFactory::createRequest(const QUrl&, QNetworkAccessManager::Operation, bool, QIODevice*)’:
/opt/otter/src/core/NetworkManagerFactory.cpp:639:23: error: ‘FollowRedirectsAttribute’ is not a member of ‘QNetworkRequest’
  request.setAttribute(QNetworkRequest::FollowRedirectsAttribute, true);
                       ^
make[2]: *** [CMakeFiles/otter-browser.dir/src/core/NetworkManagerFactory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/otter-browser.dir/all] Error 2
make: *** [all] Error 2`

Requirements of Otter says the minimum Qt version to build is 5.3. Why cannot it be build with 5.5, then? When i last updated my local repo a month ago, it worked.

**Comment by TCH68k** [comment]
Then how can i install the backported QtWebKit to Qt 5.9.1? I tried to download and build the package from qt.io, but it failed to build, with or without the ICU patch. I tried to clone and compile the 5.9 branch from the git repo and that failed too.

**Comment by Emdek** [comment]
@TCH68k, which platform? There are binaries available for Qt 5.10.

**Comment by TCH68k** [comment]
Linux, AM64. I did not found any QtWebKit binaries for Qt 5.10, nor sources. Is it supported officially again, that's why there is no additional archive?

**Comment by Emdek** [comment]
@TCH68k, ok, then it might be harder to get binaries...
master requires updated QtWebKit, from here:
https://github.com/annulen/webkit

**Comment by TCH68k** [comment]
And this is works with Qt5.10 too? I only have to fetch this repo and compile it aganist Qt5.10?

**Comment by Emdek** [comment]
@TCH68k, it should work back to at least 5.4.
Take a look at README, there is also snapshots repository, this one is 7 GB data to download...
Or use source packages for alpha2.
In case of troubles you can try to find @annulen at our IRC channel.

**Comment by TCH68k** [comment]
Okay, thank you!

**Comment by TCH68k** [comment]
I've managed to build Otter with Qt5.7.1 and WebKit 5.212 from here: https://github.com/qt/qtwebkit.git

Soon i will try the other repo with Qt5.10.1, however; why Otter tells me, that the WebKit backend is 602.1? I did not install QtWebEngine, so it should be 5.212.

**Comment by TCH68k** [comment]
I've tried to compile the "master" branch of that repo you've shown to me, however, the result is:

https://pastebin.com/PLYJMuAJ

There is no such option as "Qt5". Which port i should choose?

**Comment by lanodan** [comment]
Look at the readme[1] about the branches I guess.

1: https://github.com/annulen/webkit/blob/qtwebkit-5.212/ReadMe.md

**Comment by Emdek** [comment]
@TCH68k, 6xx is version number from Apple.

**Comment by TCH68k** [comment]
@lanodan: So, i have to switch to the branch "qtwebkit-5.212", thanks.

@Emdek: I see, but i've compiled the 5.212. Why Otter displays 602.1?

**Comment by TCH68k** [comment]
Okay, i managed to build Otter with 5.10.1 and with the annulen port of WebKit 5.212, but Otter still displays 602.1.

**Comment by Emdek** [comment]
@TCH68k, that is the correct WebKit version number for 5.212.

**Comment by TCH68k** [comment]
Oh, i see. Then i don't understand, that the other 5.212 displayed 5.212, but never mind. What matters, that it is QtWebKit and not QtWebEngine then. Thanks!

**Comment by Emdek** [comment]
@TCH68k, odd, it would have to be patched to display that one instead.
