### ISSUE TITLE
Improve URL completion

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1007]
Below are three request related to the URL completion and to the address bar in general.

1. Currently, the URL completion searches for URLs beginning by the entry. It would be practical to mimic the behavior of Firefox, where the entered text is sought everywhere in the URL plus in the title metadata.
2. Also, the old Opera had the capability to drop history entries in the completion list (there was a cross icon on the left side of each line). It would also be practical to have this feature. (At the moment, there is a context menu named “remove this icon” when you right-click on a line but it does nothing—I originally thought it was this feature but it doesn’t seem to do anything.)
3. The star used to show that the current page was bookmarked should be shown in the completion menu for each relevant line.

My last point is cosmetic: the URLs are shown in blue in the completion menu, why not display them in black (or the common text colour).

**Comment by lollox** [comment]
The second point is already implemented for what I can see...

**Comment by pierreporte** [comment]
@lollox How do you do it?

**Comment by lollox** [comment]
sorry my fault... I didn't understand you wanted the ability to remove items from the dropdown.

**Comment by Emdek** [comment]
I wonder what exactly does Opera while using it on URL completion results, when used on results from typed history dropdown it will remove entry from typed history.
So what it will do in this mode? Will it remove it from bookmarks (if it is bookmark) or from history?
Or maybe it should be just blacklisted or something?

**Comment by pierreporte** [comment]
@Emdek, I didn’t mean replacing the favicon at all.

**Comment by Emdek** [comment]
@pierreporte, so where should we show it, on the right perhaps?

**Comment by pierreporte** [comment]
Here is a picture showing where I see the elements (sorry for the extra “delete”):

![URL completion improvements](https://cloud.githubusercontent.com/assets/2029853/11609931/0f782244-9b94-11e5-8123-96e9d82f6367.png)

The star icon would be displayed right after the title of the page (with some space maybe). Note that it must be an icon and not a simple character in order to not be mistaken if the chosen character is present in the title. The button to drop the line from completion would be displayed at the very end of the line (like in Opera 12). Note that these do not appear for the search engine line.

**Comment by pierreporte** [comment]
Oops! Wrong button!

**Comment by ersi-dnd** [comment]
"My last point is cosmetic: the URLs are shown in blue in the completion menu, why not display them in black (or the common text colour)."

In my opinion this is a very important point. All colours should be inherited from somewhere. There should be no hard-coded colours. This way skins and themes will have a complete control over colours, they will harmonise as thoroughly as possible and they will be possible to customise too.

There is an issue I have with URL completion. When I delete a something from the end of the URL in the address field, then sometimes another element jumps in (from history? autocompletion?) and ruins my clean Enter. This should not happen. I should not need to modify the end (or any other spot) of the URL twice and then press Enter.

**Comment by pierreporte** [comment]
On the screenshot below is show the URL completion in Vivaldi. As you can see, the bookmarks (“signets” in French) are clearly separated from the history entries (“historique”) with titles. I think it is a better option than adding an icon like I proposed because it is more clear (the user doesn’t need to know the meaning of an icon) and the view is not overloaded.

![URL completion in Vivaldi](https://cloud.githubusercontent.com/assets/2029853/11716004/eb0afe48-9f46-11e5-8597-a61db281baff.png)

I would like to add a precision on the URL matching. As in Firefox and as not in Vivaldi, the parts in the URLs that match should be slightly highlighted.

**Comment by Emdek** [comment]
@ersi-dnd, @pierreporte, that blue comes form system palette color for links, this appears to be the best choice for existing color that has to have a contrast with background.
The only alternative appears to be to lighten main text color, but that can generate unreadable text like in #537.

**Comment by Zero3K** [comment]
I would also like to see the 1st suggestion implemented in a later version.

**Comment by pierreporte** [comment]
There are some issues since the commit 2b6c83336ca82252f45eb572bae0906416ccd493.

1. The completion menu is too short. Even with only two elements in it, there is a scrolling bar.
2. It is impossible to dismiss the completion menu by clicking somewhere (in the Otter Browser window or elsewhere).

Nice to see this implemented BTW.

While I am here, I would make a suggestion about the search engine category. For now, it displays only the default search engine with the category title “Search with X”. Why not adding links for other search engines? It would be like this:

> Search with X or Y / Z / A / B / C / …

Y, Z, A, B, and C, when clicked, runs the search with the corresponding engines. Of course, you can specify the right keyword in the first place but users who changed their minds or didn’t even set keywords may find this practical. That could cause some problems if the user has set a lot of search engines though.

**Comment by pierreporte** [comment]
Cosmetic issue for the completion menu: the 1 pixel border is drawn only on the top and right sides, the bottom and left sides are completely white. It may be theme dependant.

The focus issue is still present.

The new option to chose the layout of the completion menu (Compact, i.e. standard Otter layout, and columns, i.e. Vivaldi layout) may be slightly unclear. Why not replace the drop-down selector with radio buttons which allows more description?

* **Compact.** Titles right after the URLs
* **Columns.** Titles aligned in a column.

**Comment by pierreporte** [comment]
A precision for the focus issue. If you click on the little arrow on the rightmost side of the URL field, then the behaviour is good. It is only with the completion menu appearing while typing that the issue is present.

**Comment by bajasoft** [comment]
@pierreporte: Unfortunately I'm not able to replicate your issue with focus, it works ok on my side (Windows with Qt 5.6)

**Comment by pierreporte** [comment]
The issue #1127 (Advanced address bar shortcuts) is strongly linked to this one since the presented keywords are actually meant to filter completion entries.

**Comment by midluk** [comment]
@bajasoft, 641b06adde1318c8507ffe36a35a14da02611acc fails to compile:
```
src/modules/widgets/address/AddressWidget.cpp: In member function ‘virtual void Otter::AddressWidget::keyPressEvent(QKeyEvent*)’:
src/modules/widgets/address/AddressWidget.cpp:325:27: error: no match for call to ‘(const QString) ()’
   const QString text(text().trimmed());
```

**Comment by Emdek** [comment]
@midluk, fixed.

**Comment by pierreporte** [comment]
The new highlighting feature is a great addition, however I don’t find it very clear. On my system, the bold font used does not have enough contrast with the regular font. In fact, I was unable to notice the highlight at first sight. The font I use is Cantarell, the default for Gnome. (I have the same problem with Firefox by the way.)

I think it would be best to underline the highlighted part on top on the bold face. Or maybe a background variation like the text search feature.

**Comment by Emdek** [comment]
@pierreporte, that sounds more like issue with that font itself. ;-)
Some experiments with colors might be a good idea, but probably we should focus on font color, perhaps use of ``QColor::darker()`` for highlighted part could be good enough.
